### ISSUE TITLE
Error: Cannot find module '@mohayonao/wave-tables'

### ISSUE THREAD

**Issue by lukehorvat** [mohayonao/wave-tables#1]
Hi, I'd like to use this npm package. But I get a `Cannot find module '@mohayonao/wave-tables'` error when doing `require('@mohayonao/wave-tables')`. I believe it is because you haven't got a main `index.js` script.

Could you fix this (or I can send you a pull request if you like)? Thanks.

**Comment by lukehorvat** [comment]
Okay, just realized I can do `require('@mohayonao/wave-tables/Bass')` and it works.

Nonetheless it would still be nice to have a main script that exports all of the JSON files (so that you can iterate over all of them programmatically if necessary), or at least a note in the readme that this is how you should `require` files from the package.

**Comment by mohayonao** [comment]
Hi, thanks for your suggestion.

I've added index.js to load data programmatically.

**Comment by lukehorvat** [comment]
Exactly what I needed. 👍  Cheers.
